apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      name: backend-service
      labels:
        app: backend-service
    spec:
      initContainers:
        - name: init-backend-service
          image: CONTAINER_IMAGE
          envFrom:
            - configMapRef:
                name: backend-service
          imagePullPolicy: "Always"
          command: ["sh", "-c", "npm run db:migrate"]
      containers:
        - name: backend-service
          image: CONTAINER_IMAGE
          envFrom:
            - configMapRef:
                name: backend-service
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000